name: ebook_app
description: An eBook reader application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  material_color_utilities: ^0.5.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  vocsy_epub_viewer: ^2.0.0
  widget_mask: ^1.0.0+0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
